# Conceptual model

1. Your team is able to collect data about the below variables. The data that your team has collected can be found [here](https://homes.cs.washington.edu/~emjun/income_final.csv).
```{r}
library(rTisane)

person <- Unit(name = "person")
# Age: Continuous measure
age <- continuous(unit = person, "Age")
# Race: There are 5 categories: White, Black/African American, American Indian or Alaska Native, Asian or Pacific Islander, Mixed Race
race <- categories(unit = person, "Race", cardinality = 9)
# Highest Education Completed: 5 categories: Grade 12, 1 year of college, 2 years of college, 4 years of college, 5+ years of colleges
edu <- categories(unit = person, "Education", order=list("Grade 12", "1 year of college", "2 years of college", "4 years of college", "5+ years of college"))
# Current Employment Status: 3 categories: N/A, Works for wage, Self-employed
employ <- categories(unit=person, "Employment", cardinality=2)
# Sex: 2 categories: Male, Female
sex <- categories(unit = person, "Sex",cardinality = 2)
# Income: Continuous measure
income <- continuous(unit = person, "Income")
```

2. Specify your conceptual model. 
```{r}
cm <- ConceptualModel()
cel<-causes(cause=edu, effect=income, when=equals(edu, 'Grade 12'), then=decreases(income))
assume(cm, cel) # strong belief that a grade 12 participant will have low income

ceh<-causes(cause=edu, effect=income, when=equals(edu, '5+ years of college'), then=increases(income))
hypothesize(cm, ceh) # participant with 5+ years of experience after college should have higher income 

# Add conceptual relationships here
```

3. Run the above code snippets before running this one:
```{r}
updatedCM <- checkAndRefineConceptualModel(cm) # Check and refine your conceptual model
```
