# Conceptual model

1. Your team is able to collect data about the below variables. The data that your team has collected can be found [here](https://homes.cs.washington.edu/~emjun/summative_eval/income.csv).
```{r}
library(rTisane)
age <- continuous("Age")
race <- categories("Race")
edu <- categories("Education")
occupation <- categories("Occupation")
sex <- categories("Sex")
income <- continuous("Income")
```

2. Specify your conceptual model. 
```{r}
cm <- ConceptualModel()
cel<-causes(causes=edu, effect=income, when=equals(edu, 'Grade 12'), then=decreases(income))
assume(cm, cel) # strong belief that a grade 12 participant will have low income

ceh<-causes(causes=edu, effect=income, when=equals(edu, '5+ years of college'), then=increases(income))
hypothesize(cm, ceh) # participant with 5+ years of experience after college should have higher income 


# Add conceptual relationships here
```

3. Run the above code snippets before running this one:
```{r}
updatedCM <- checkAndRefine(cm) # Check and refine your conceptual model
```
