# Tutorial 
Answer the questions below. Feel free to refer back to the Overview. 

Consider the following scenario from the Overview: 
> You are interested in understanding the influence of age on physical endurance, as measured by the number of minutes adults can run before hitting too high a heart rate. To this end, you collect data from 245 adults about their age, sex, SES (as "low", "medium", or "high") and the nubmer of years they self-report having done vigorous exercise regularly.
Note: This example is adapted from Cohen, Cohen, West, Aiken 2003.

## Step 1: Declare variables
```R
# Type in here
```

## Step 2: Specify conceptual relationships 
For the sake of this tutorial, let's make sure you are familiar with the API. Use each construct at least once: ``causes``, ``relates``, ``assume``, ``hypothesize``. 
Use the optional ``when`` and ``then`` parameters when specifying at least one conceptual relationship.
```R
# Type in here
```

## Step 3: Query for a statistical model
```R
# Type in here
```