# Conceptual model

1. Your team is able to collect data about the below variables. The data that your team has collected can be found [here](https://homes.cs.washington.edu/~emjun/summative_eval/income.csv).
```{r}
library(rTisane)
person <- Unit(name = "person")
age <- continuous(unit = person, "Age")
race <- categories(unit = person, "Race", cardinality = 5)
edu <- categories(unit = person, "Education",cardinality = 5)
occupation <- categories(unit = person, "Occupation",cardinality = 5)
sex <- categories(unit = person, "Sex",cardinality = 5)
income <- continuous(unit = person, "Income")
```

2. Specify your conceptual model. 
```{r}
cm <- ConceptualModel()
cm <- assume(cm,causes(cause=occupation, effect=income))
cm <- hypothesize(cm,relates(age, occupation))
cm <- hypothesize(cm,relates(race, occupation))
cm <- assume(cm,causes(cause = edu, effect = occupation))
cm <- hypothesize(cm,relates(sex, occupation))


# Add conceptual relationships here
```

3. Run the above code snippets before running this one:
```{r}
updatedCM <- checkAndRefineConceptualModel(cm) # Check and refine your conceptual model

```
