# Conceptual model

1. Your team is able to collect data about the below variables. The data that your team has collected can be found [here](https://homes.cs.washington.edu/~emjun/income_final.csv).
```{r}
library(rTisane)
# devtools::load_all()
source("~/Git/rTisane/conceptualDisambiguation/app.R")

person <- Unit(name = "person")
# Age: Continuous measure
age <- continuous(unit = person, "Age")
# Race: There are 5 categories: White, Black/African American, American Indian or Alaska Native, Asian or Pacific Islander, Mixed Race
race <- categories(unit = person, "Race", cardinality = 9)
# Highest Education Completed: 5 categories: Grade 12, 1 year of college, 2 years of college, 4 years of college, 5+ years of colleges
edu <- categories(unit = person, "Education", order=list("Grade 12", "1 year of college", "2 years of college", "4 years of college", "5+ years of college"))
# Current Employment Status: 3 categories: N/A, Works for wage, Self-employed
employ <- categories(unit=person, "Employment", cardinality=2)
# Sex: 2 categories: Male, Female
sex <- categories(unit = person, "Sex",cardinality = 2)
# Income: Continuous measure
income <- continuous(unit = person, "Income")
```

2. Specify your conceptual model. 
```{r}
cm <- ConceptualModel()
# causes(
#     cause=edu, effect=income,
#     when=equals(edu, '5+ years of college'),
#     then=increases(income))
# 
# relates(
#     lhs=edu, rhs=income,
#     when=equals(edu, '4 years of college'),
#     then=increases(income))
# # Add conceptual relationships here
# 
# cm <- ConceptualModel()
# ...
cr <- causes(edu, income)
cm <- hypothesize(cm, cr) # cm refers to the Conceptual Model you declared previously and are adding this relationship to
cr <- causes(employ, income)
cm <- hypothesize(cm, cr)

cm <- interacts(cm, age, race,sex, dv=income)

```

3. Run the above code snippets before running this one:
```{r}
updatedCM <- checkAndRefineConceptualModel(cm) # Check and refine your conceptual model
```
